### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [austinwagner/sublime-sourcepawn#9]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by austinwagner** [comment]
I must not have known how much I dislike the GNU philosophy when I licensed this repo. It's now under MIT, so use the code in here however you want now. :smiley:

**Comment by arfon** [comment]
👍 many thanks!
